department_rules! {
    "Layout";
    empty_line_after_magic_comment => ("EmptyLineAfterMagicComment", Convention),
    access_modifier_indentation => ("AccessModifierIndentation", Convention),
    argument_alignment => ("ArgumentAlignment", Convention),
    array_alignment => ("ArrayAlignment", Convention),
    begin_end_alignment => ("BeginEndAlignment", Warning),
    case_indentation => ("CaseIndentation", Convention),
    def_end_alignment => ("DefEndAlignment", Warning),
    dot_position => ("DotPosition", Convention),
    else_alignment => ("ElseAlignment", Convention),
    empty_line_after_guard_clause => ("EmptyLineAfterGuardClause", Convention),
    end_alignment => ("EndAlignment", Warning),
    empty_line_between_defs => ("EmptyLineBetweenDefs", Convention),
    empty_lines => ("EmptyLines", Convention),
    empty_lines_around_attribute_accessor => ("EmptyLinesAroundAttributeAccessor", Convention),
    empty_lines_around_access_modifier => ("EmptyLinesAroundAccessModifier", Convention),
    end_of_line => ("EndOfLine", Convention),
    first_array_element_indentation => ("FirstArrayElementIndentation", Convention),
    first_hash_element_indentation => ("FirstHashElementIndentation", Convention),
    hash_alignment => ("HashAlignment", Convention),
    indentation_consistency => ("IndentationConsistency", Convention),
    indentation_width => ("IndentationWidth", Convention),
    line_length => ("LineLength", Convention),
    multiline_array_brace_layout => ("MultilineArrayBraceLayout", Convention),
    multiline_hash_brace_layout => ("MultilineHashBraceLayout", Convention),
    multiline_method_call_brace_layout => ("MultilineMethodCallBraceLayout", Convention),
    multiline_method_definition_brace_layout => ("MultilineMethodDefinitionBraceLayout", Convention),
    space_after_comma => ("SpaceAfterComma", Convention),
    space_around_operators => ("SpaceAroundOperators", Convention),
    space_in_lambda_literal => ("SpaceInLambdaLiteral", Convention),
    space_inside_array_literal_brackets => ("SpaceInsideArrayLiteralBrackets", Convention),
    space_inside_block_braces => ("SpaceInsideBlockBraces", Convention),
    space_inside_parens => ("SpaceInsideParens", Convention),
    space_inside_percent_literal_delimiters => ("SpaceInsidePercentLiteralDelimiters", Convention),
    trailing_empty_lines => ("TrailingEmptyLines", Convention),
    trailing_whitespace => ("TrailingWhitespace", Convention),
}

mod multiline_brace;
mod support;
