department_rules! {
    "Layout";
    empty_line_after_magic_comment => ("EmptyLineAfterMagicComment", Convention),
    access_modifier_indentation => ("AccessModifierIndentation", Convention),
    argument_alignment => ("ArgumentAlignment", Convention),
    array_alignment => ("ArrayAlignment", Convention),
    assignment_indentation => ("AssignmentIndentation", Convention),
    begin_end_alignment => ("BeginEndAlignment", Warning),
    block_end_newline => ("BlockEndNewline", Convention),
    case_indentation => ("CaseIndentation", Convention),
    closing_heredoc_indentation => ("ClosingHeredocIndentation", Convention),
    closing_parenthesis_indentation => ("ClosingParenthesisIndentation", Convention),
    comment_indentation => ("CommentIndentation", Convention),
    condition_position => ("ConditionPosition", Warning),
    def_end_alignment => ("DefEndAlignment", Warning),
    dot_position => ("DotPosition", Convention),
    else_alignment => ("ElseAlignment", Convention),
    empty_comment => ("EmptyComment", Convention),
    empty_line_after_guard_clause => ("EmptyLineAfterGuardClause", Convention),
    rescue_ensure_alignment => ("RescueEnsureAlignment", Convention),
    end_alignment => ("EndAlignment", Warning),
    empty_line_between_defs => ("EmptyLineBetweenDefs", Convention),
    empty_lines => ("EmptyLines", Convention),
    empty_lines_around_attribute_accessor => ("EmptyLinesAroundAttributeAccessor", Convention),
    empty_lines_around_access_modifier => ("EmptyLinesAroundAccessModifier", Convention),
    empty_lines_around_arguments => ("EmptyLinesAroundArguments", Convention),
    empty_lines_around_begin_body => ("EmptyLinesAroundBeginBody", Convention),
    empty_lines_around_block_body => ("EmptyLinesAroundBlockBody", Convention),
    empty_lines_around_class_body => ("EmptyLinesAroundClassBody", Convention),
    empty_lines_around_exception_handling_keywords => ("EmptyLinesAroundExceptionHandlingKeywords", Convention),
    empty_lines_around_method_body => ("EmptyLinesAroundMethodBody", Convention),
    empty_lines_around_module_body => ("EmptyLinesAroundModuleBody", Convention),
    end_of_line => ("EndOfLine", Convention),
    first_argument_indentation => ("FirstArgumentIndentation", Convention),
    first_array_element_indentation => ("FirstArrayElementIndentation", Convention),
    first_hash_element_indentation => ("FirstHashElementIndentation", Convention),
    first_parameter_indentation => ("FirstParameterIndentation", Convention),
    hash_alignment => ("HashAlignment", Convention),
    heredoc_indentation => ("HeredocIndentation", Convention),
    indentation_consistency => ("IndentationConsistency", Convention),
    indentation_style => ("IndentationStyle", Convention),
    indentation_width => ("IndentationWidth", Convention),
    initial_indentation => ("InitialIndentation", Convention),
    leading_comment_space => ("LeadingCommentSpace", Convention),
    leading_empty_lines => ("LeadingEmptyLines", Convention),
    line_length => ("LineLength", Convention),
    multiline_array_brace_layout => ("MultilineArrayBraceLayout", Convention),
    multiline_block_layout => ("MultilineBlockLayout", Convention),
    multiline_hash_brace_layout => ("MultilineHashBraceLayout", Convention),
    multiline_method_call_brace_layout => ("MultilineMethodCallBraceLayout", Convention),
    multiline_method_call_indentation => ("MultilineMethodCallIndentation", Convention),
    multiline_method_definition_brace_layout => ("MultilineMethodDefinitionBraceLayout", Convention),
    multiline_operation_indentation => ("MultilineOperationIndentation", Convention),
    parameter_alignment => ("ParameterAlignment", Convention),
    space_after_colon => ("SpaceAfterColon", Convention),
    space_after_comma => ("SpaceAfterComma", Convention),
    space_after_method_name => ("SpaceAfterMethodName", Convention),
    space_after_not => ("SpaceAfterNot", Convention),
    space_after_semicolon => ("SpaceAfterSemicolon", Convention),
    space_around_operators => ("SpaceAroundOperators", Convention),
    space_around_method_call_operator => ("SpaceAroundMethodCallOperator", Convention),
    space_around_block_parameters => ("SpaceAroundBlockParameters", Convention),
    space_around_equals_in_parameter_default => ("SpaceAroundEqualsInParameterDefault", Convention),
    space_around_keyword => ("SpaceAroundKeyword", Convention),
    space_before_first_arg => ("SpaceBeforeFirstArg", Convention),
    space_before_comma => ("SpaceBeforeComma", Convention),
    space_before_comment => ("SpaceBeforeComment", Convention),
    space_before_block_braces => ("SpaceBeforeBlockBraces", Convention),
    space_before_semicolon => ("SpaceBeforeSemicolon", Convention),
    space_in_lambda_literal => ("SpaceInLambdaLiteral", Convention),
    space_inside_array_literal_brackets => ("SpaceInsideArrayLiteralBrackets", Convention),
    space_inside_array_percent_literal => ("SpaceInsideArrayPercentLiteral", Convention),
    space_inside_block_braces => ("SpaceInsideBlockBraces", Convention),
    space_inside_hash_literal_braces => ("SpaceInsideHashLiteralBraces", Convention),
    space_inside_parens => ("SpaceInsideParens", Convention),
    space_inside_percent_literal_delimiters => ("SpaceInsidePercentLiteralDelimiters", Convention),
    space_inside_range_literal => ("SpaceInsideRangeLiteral", Convention),
    space_inside_reference_brackets => ("SpaceInsideReferenceBrackets", Convention),
    space_inside_string_interpolation => ("SpaceInsideStringInterpolation", Convention),
    trailing_empty_lines => ("TrailingEmptyLines", Convention),
    trailing_whitespace => ("TrailingWhitespace", Convention),
}

mod empty_lines_around_body;
mod multiline_brace;
mod multiline_expression;
mod support;
