//! Ruby's exception hierarchy, which `Lint/ShadowedException` reads through `Kernel.const_get`.
//!
//! Upstream resolves each rescued name against the constants of the process RuboCop itself runs
//! in, and compares the classes with `Module#<=>`. Listed here are the classes every such process
//! has: Ruby's own, and the ones the standard library RuboCop loads defines -- `Psych`, which
//! reads the configuration, and the rest that come with it. What a *particular* run adds beyond
//! that (an application's own classes, a gem's) is not knowable here, and a name this table does
//! not know answers `nil`, exactly as an unresolvable constant does upstream: a `nil` never makes
//! a group unsorted or multi-levelled, so an unknown name is simply not shadowed by anything.

/// Every class under `Exception`, paired with its superclass. `Object` and `BasicObject` are
/// included so that a `rescue Object` compares the way upstream's does.
const HIERARCHY: &[(&str, &str)] = &[
    ("ArgumentError", "StandardError"),
    ("BasicObject", ""),
    ("ClosedQueueError", "StopIteration"),
    ("Date::Error", "ArgumentError"),
    ("EOFError", "IOError"),
    ("Encoding::CompatibilityError", "EncodingError"),
    ("Encoding::ConverterNotFoundError", "EncodingError"),
    ("Encoding::InvalidByteSequenceError", "EncodingError"),
    ("Encoding::UndefinedConversionError", "EncodingError"),
    ("EncodingError", "StandardError"),
    ("Errno::E2BIG", "SystemCallError"),
    ("Errno::EACCES", "SystemCallError"),
    ("Errno::EADDRINUSE", "SystemCallError"),
    ("Errno::EADDRNOTAVAIL", "SystemCallError"),
    ("Errno::EAFNOSUPPORT", "SystemCallError"),
    ("Errno::EAGAIN", "SystemCallError"),
    ("Errno::EALREADY", "SystemCallError"),
    ("Errno::EAUTH", "SystemCallError"),
    ("Errno::EBADARCH", "SystemCallError"),
    ("Errno::EBADEXEC", "SystemCallError"),
    ("Errno::EBADF", "SystemCallError"),
    ("Errno::EBADMACHO", "SystemCallError"),
    ("Errno::EBADMSG", "SystemCallError"),
    ("Errno::EBADRPC", "SystemCallError"),
    ("Errno::EBUSY", "SystemCallError"),
    ("Errno::ECANCELED", "SystemCallError"),
    ("Errno::ECHILD", "SystemCallError"),
    ("Errno::ECONNABORTED", "SystemCallError"),
    ("Errno::ECONNREFUSED", "SystemCallError"),
    ("Errno::ECONNRESET", "SystemCallError"),
    ("Errno::EDEADLK", "SystemCallError"),
    ("Errno::EDESTADDRREQ", "SystemCallError"),
    ("Errno::EDEVERR", "SystemCallError"),
    ("Errno::EDOM", "SystemCallError"),
    ("Errno::EDQUOT", "SystemCallError"),
    ("Errno::EEXIST", "SystemCallError"),
    ("Errno::EFAULT", "SystemCallError"),
    ("Errno::EFBIG", "SystemCallError"),
    ("Errno::EFTYPE", "SystemCallError"),
    ("Errno::EHOSTDOWN", "SystemCallError"),
    ("Errno::EHOSTUNREACH", "SystemCallError"),
    ("Errno::EIDRM", "SystemCallError"),
    ("Errno::EILSEQ", "SystemCallError"),
    ("Errno::EINPROGRESS", "SystemCallError"),
    ("Errno::EINTR", "SystemCallError"),
    ("Errno::EINVAL", "SystemCallError"),
    ("Errno::EIO", "SystemCallError"),
    ("Errno::EISCONN", "SystemCallError"),
    ("Errno::EISDIR", "SystemCallError"),
    ("Errno::ELOOP", "SystemCallError"),
    ("Errno::EMFILE", "SystemCallError"),
    ("Errno::EMLINK", "SystemCallError"),
    ("Errno::EMSGSIZE", "SystemCallError"),
    ("Errno::EMULTIHOP", "SystemCallError"),
    ("Errno::ENAMETOOLONG", "SystemCallError"),
    ("Errno::ENEEDAUTH", "SystemCallError"),
    ("Errno::ENETDOWN", "SystemCallError"),
    ("Errno::ENETRESET", "SystemCallError"),
    ("Errno::ENETUNREACH", "SystemCallError"),
    ("Errno::ENFILE", "SystemCallError"),
    ("Errno::ENOATTR", "SystemCallError"),
    ("Errno::ENOBUFS", "SystemCallError"),
    ("Errno::ENODATA", "SystemCallError"),
    ("Errno::ENODEV", "SystemCallError"),
    ("Errno::ENOENT", "SystemCallError"),
    ("Errno::ENOEXEC", "SystemCallError"),
    ("Errno::ENOLCK", "SystemCallError"),
    ("Errno::ENOLINK", "SystemCallError"),
    ("Errno::ENOMEM", "SystemCallError"),
    ("Errno::ENOMSG", "SystemCallError"),
    ("Errno::ENOPOLICY", "SystemCallError"),
    ("Errno::ENOPROTOOPT", "SystemCallError"),
    ("Errno::ENOSPC", "SystemCallError"),
    ("Errno::ENOSR", "SystemCallError"),
    ("Errno::ENOSTR", "SystemCallError"),
    ("Errno::ENOSYS", "SystemCallError"),
    ("Errno::ENOTBLK", "SystemCallError"),
    ("Errno::ENOTCAPABLE", "SystemCallError"),
    ("Errno::ENOTCONN", "SystemCallError"),
    ("Errno::ENOTDIR", "SystemCallError"),
    ("Errno::ENOTEMPTY", "SystemCallError"),
    ("Errno::ENOTRECOVERABLE", "SystemCallError"),
    ("Errno::ENOTSOCK", "SystemCallError"),
    ("Errno::ENOTSUP", "SystemCallError"),
    ("Errno::ENOTTY", "SystemCallError"),
    ("Errno::ENXIO", "SystemCallError"),
    ("Errno::EOPNOTSUPP", "SystemCallError"),
    ("Errno::EOVERFLOW", "SystemCallError"),
    ("Errno::EOWNERDEAD", "SystemCallError"),
    ("Errno::EPERM", "SystemCallError"),
    ("Errno::EPFNOSUPPORT", "SystemCallError"),
    ("Errno::EPIPE", "SystemCallError"),
    ("Errno::EPROCLIM", "SystemCallError"),
    ("Errno::EPROCUNAVAIL", "SystemCallError"),
    ("Errno::EPROGMISMATCH", "SystemCallError"),
    ("Errno::EPROGUNAVAIL", "SystemCallError"),
    ("Errno::EPROTO", "SystemCallError"),
    ("Errno::EPROTONOSUPPORT", "SystemCallError"),
    ("Errno::EPROTOTYPE", "SystemCallError"),
    ("Errno::EPWROFF", "SystemCallError"),
    ("Errno::EQFULL", "SystemCallError"),
    ("Errno::ERANGE", "SystemCallError"),
    ("Errno::EREMOTE", "SystemCallError"),
    ("Errno::EROFS", "SystemCallError"),
    ("Errno::ERPCMISMATCH", "SystemCallError"),
    ("Errno::ESHLIBVERS", "SystemCallError"),
    ("Errno::ESHUTDOWN", "SystemCallError"),
    ("Errno::ESOCKTNOSUPPORT", "SystemCallError"),
    ("Errno::ESPIPE", "SystemCallError"),
    ("Errno::ESRCH", "SystemCallError"),
    ("Errno::ESTALE", "SystemCallError"),
    ("Errno::ETIME", "SystemCallError"),
    ("Errno::ETIMEDOUT", "SystemCallError"),
    ("Errno::ETOOMANYREFS", "SystemCallError"),
    ("Errno::ETXTBSY", "SystemCallError"),
    ("Errno::EUSERS", "SystemCallError"),
    ("Errno::EXDEV", "SystemCallError"),
    ("Errno::NOERROR", "SystemCallError"),
    ("Exception", "Object"),
    ("FiberError", "StandardError"),
    ("FloatDomainError", "RangeError"),
    ("FrozenError", "RuntimeError"),
    ("Gem::CommandLineError", "Gem::Exception"),
    ("Gem::ConflictError", "Gem::LoadError"),
    ("Gem::DependencyError", "Gem::Exception"),
    ("Gem::DependencyRemovalException", "Gem::Exception"),
    ("Gem::DependencyResolutionError", "Gem::DependencyError"),
    ("Gem::DocumentError", "Gem::Exception"),
    ("Gem::EndOfYAMLException", "Gem::Exception"),
    ("Gem::Exception", "RuntimeError"),
    ("Gem::FilePermissionError", "Gem::Exception"),
    ("Gem::FormatException", "Gem::Exception"),
    ("Gem::GemNotFoundException", "Gem::Exception"),
    ("Gem::GemNotInHomeException", "Gem::Exception"),
    ("Gem::ImpossibleDependenciesError", "Gem::Exception"),
    ("Gem::InstallError", "Gem::Exception"),
    ("Gem::InvalidSpecificationException", "Gem::Exception"),
    ("Gem::LoadError", "LoadError"),
    ("Gem::MissingSpecError", "Gem::LoadError"),
    ("Gem::MissingSpecVersionError", "Gem::MissingSpecError"),
    ("Gem::OperationNotSupportedError", "Gem::Exception"),
    ("Gem::RemoteError", "Gem::Exception"),
    ("Gem::RemoteInstallationCancelled", "Gem::Exception"),
    ("Gem::RemoteInstallationSkipped", "Gem::Exception"),
    ("Gem::RemoteSourceException", "Gem::Exception"),
    ("Gem::Requirement::BadRequirementError", "ArgumentError"),
    ("Gem::RubyVersionMismatch", "Gem::Exception"),
    ("Gem::RuntimeRequirementNotMetError", "Gem::InstallError"),
    (
        "Gem::SpecificGemNotFoundException",
        "Gem::GemNotFoundException",
    ),
    ("Gem::SystemExitException", "SystemExit"),
    ("Gem::UninstallError", "Gem::Exception"),
    ("Gem::UnknownCommandError", "Gem::Exception"),
    ("Gem::UnsatisfiableDependencyError", "Gem::DependencyError"),
    ("Gem::VerificationError", "Gem::Exception"),
    ("Gem::WebauthnVerificationError", "Gem::Exception"),
    ("IO::Buffer::AccessError", "RuntimeError"),
    ("IO::Buffer::AllocationError", "RuntimeError"),
    ("IO::Buffer::InvalidatedError", "RuntimeError"),
    ("IO::Buffer::LockedError", "RuntimeError"),
    ("IO::Buffer::MaskError", "ArgumentError"),
    ("IO::EAGAINWaitReadable", "Errno::EAGAIN"),
    ("IO::EAGAINWaitWritable", "Errno::EAGAIN"),
    ("IO::EINPROGRESSWaitReadable", "Errno::EINPROGRESS"),
    ("IO::EINPROGRESSWaitWritable", "Errno::EINPROGRESS"),
    ("IO::TimeoutError", "IOError"),
    ("IOError", "StandardError"),
    ("IPAddr::AddressFamilyError", "IPAddr::Error"),
    ("IPAddr::Error", "ArgumentError"),
    ("IPAddr::InvalidAddressError", "IPAddr::Error"),
    ("IPAddr::InvalidPrefixError", "IPAddr::InvalidAddressError"),
    ("IndexError", "StandardError"),
    ("Interrupt", "SignalException"),
    ("JSON::GeneratorError", "JSON::JSONError"),
    ("JSON::JSONError", "StandardError"),
    ("JSON::NestingError", "JSON::ParserError"),
    ("JSON::ParserError", "JSON::JSONError"),
    ("KeyError", "IndexError"),
    ("LoadError", "ScriptError"),
    ("LocalJumpError", "StandardError"),
    ("Math::DomainError", "StandardError"),
    ("NameError", "StandardError"),
    ("Net::HTTPBadResponse", "StandardError"),
    ("Net::HTTPClientException", "Net::ProtoServerError"),
    ("Net::HTTPError", "Net::ProtocolError"),
    ("Net::HTTPFatalError", "Net::ProtoFatalError"),
    ("Net::HTTPHeaderSyntaxError", "StandardError"),
    ("Net::HTTPRetriableError", "Net::ProtoRetriableError"),
    ("Net::OpenTimeout", "Timeout::Error"),
    ("Net::ProtoAuthError", "Net::ProtocolError"),
    ("Net::ProtoCommandError", "Net::ProtocolError"),
    ("Net::ProtoFatalError", "Net::ProtocolError"),
    ("Net::ProtoRetriableError", "Net::ProtocolError"),
    ("Net::ProtoServerError", "Net::ProtocolError"),
    ("Net::ProtoSyntaxError", "Net::ProtocolError"),
    ("Net::ProtoUnknownError", "Net::ProtocolError"),
    ("Net::ProtocolError", "StandardError"),
    ("Net::ReadTimeout", "Timeout::Error"),
    ("Net::WriteTimeout", "Timeout::Error"),
    ("NoMatchingPatternError", "StandardError"),
    ("NoMatchingPatternKeyError", "NoMatchingPatternError"),
    ("NoMemoryError", "Exception"),
    ("NoMethodError", "NameError"),
    ("NotImplementedError", "ScriptError"),
    ("Object", "BasicObject"),
    ("OpenSSL::ASN1::ASN1Error", "OpenSSL::OpenSSLError"),
    ("OpenSSL::BNError", "OpenSSL::OpenSSLError"),
    (
        "OpenSSL::Cipher::AuthTagError",
        "OpenSSL::Cipher::CipherError",
    ),
    ("OpenSSL::Cipher::CipherError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::ConfigError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::Digest::DigestError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::HMACError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::KDF::KDFError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::Netscape::SPKIError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::OCSP::OCSPError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::OpenSSLError", "StandardError"),
    ("OpenSSL::PKCS12::PKCS12Error", "OpenSSL::OpenSSLError"),
    ("OpenSSL::PKCS7::PKCS7Error", "OpenSSL::OpenSSLError"),
    ("OpenSSL::PKey::EC::Group::Error", "OpenSSL::OpenSSLError"),
    ("OpenSSL::PKey::EC::Point::Error", "OpenSSL::OpenSSLError"),
    ("OpenSSL::PKey::PKeyError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::Provider::ProviderError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::Random::RandomError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::SSL::SSLError", "OpenSSL::OpenSSLError"),
    (
        "OpenSSL::SSL::SSLErrorWaitReadable",
        "OpenSSL::SSL::SSLError",
    ),
    (
        "OpenSSL::SSL::SSLErrorWaitWritable",
        "OpenSSL::SSL::SSLError",
    ),
    (
        "OpenSSL::SSL::Session::SessionError",
        "OpenSSL::OpenSSLError",
    ),
    (
        "OpenSSL::Timestamp::TimestampError",
        "OpenSSL::OpenSSLError",
    ),
    ("OpenSSL::X509::AttributeError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::CRLError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::CertificateError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::ExtensionError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::NameError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::RequestError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::RevokedError", "OpenSSL::OpenSSLError"),
    ("OpenSSL::X509::StoreError", "OpenSSL::OpenSSLError"),
    (
        "OptionParser::AmbiguousArgument",
        "OptionParser::InvalidArgument",
    ),
    ("OptionParser::AmbiguousOption", "OptionParser::ParseError"),
    ("OptionParser::InvalidArgument", "OptionParser::ParseError"),
    ("OptionParser::InvalidOption", "OptionParser::ParseError"),
    ("OptionParser::MissingArgument", "OptionParser::ParseError"),
    ("OptionParser::NeedlessArgument", "OptionParser::ParseError"),
    ("OptionParser::ParseError", "RuntimeError"),
    ("Parallel::Break", "StandardError"),
    ("Parallel::DeadWorker", "StandardError"),
    ("Parallel::Kill", "Parallel::Break"),
    ("Parallel::UndumpableException", "StandardError"),
    ("Psych::AliasesNotEnabled", "Psych::BadAlias"),
    ("Psych::AnchorNotDefined", "Psych::BadAlias"),
    ("Psych::BadAlias", "Psych::Exception"),
    ("Psych::DisallowedClass", "Psych::Exception"),
    ("Psych::Exception", "RuntimeError"),
    ("Psych::SyntaxError", "Psych::Exception"),
    ("Ractor::ClosedError", "StopIteration"),
    ("Ractor::Error", "RuntimeError"),
    ("Ractor::IsolationError", "Ractor::Error"),
    ("Ractor::MovedError", "Ractor::Error"),
    ("Ractor::RemoteError", "Ractor::Error"),
    ("Ractor::UnsafeError", "Ractor::Error"),
    ("RangeError", "StandardError"),
    (
        "Regexp::Expression::Conditional::TooManyBranches",
        "Regexp::Parser::Error",
    ),
    ("Regexp::Parser::Error", "StandardError"),
    ("Regexp::Parser::ParserError", "Regexp::Parser::Error"),
    (
        "Regexp::Parser::UnknownTokenError",
        "Regexp::Parser::ParserError",
    ),
    (
        "Regexp::Parser::UnknownTokenTypeError",
        "Regexp::Parser::ParserError",
    ),
    (
        "Regexp::Scanner::InvalidBackrefError",
        "Regexp::Scanner::ValidationError",
    ),
    (
        "Regexp::Scanner::InvalidGroupError",
        "Regexp::Scanner::ValidationError",
    ),
    (
        "Regexp::Scanner::InvalidGroupOption",
        "Regexp::Scanner::ValidationError",
    ),
    (
        "Regexp::Scanner::InvalidSequenceError",
        "Regexp::Scanner::ValidationError",
    ),
    (
        "Regexp::Scanner::PrematureEndError",
        "Regexp::Scanner::ScannerError",
    ),
    ("Regexp::Scanner::ScannerError", "Regexp::Parser::Error"),
    (
        "Regexp::Scanner::UnknownPosixClassError",
        "Regexp::Scanner::ValidationError",
    ),
    (
        "Regexp::Scanner::UnknownUnicodePropertyError",
        "Regexp::Scanner::ValidationError",
    ),
    (
        "Regexp::Scanner::ValidationError",
        "Regexp::Scanner::ScannerError",
    ),
    (
        "Regexp::Syntax::InvalidVersionNameError",
        "Regexp::Syntax::SyntaxError",
    ),
    (
        "Regexp::Syntax::NotImplementedError",
        "Regexp::Syntax::SyntaxError",
    ),
    ("Regexp::Syntax::SyntaxError", "Regexp::Parser::Error"),
    (
        "Regexp::Syntax::UnknownSyntaxNameError",
        "Regexp::Syntax::SyntaxError",
    ),
    ("Regexp::TimeoutError", "RegexpError"),
    ("RegexpError", "StandardError"),
    ("Resolv::DNS::Config::NXDomain", "Resolv::ResolvError"),
    (
        "Resolv::DNS::Config::OtherResolvError",
        "Resolv::ResolvError",
    ),
    ("Resolv::DNS::DecodeError", "StandardError"),
    ("Resolv::DNS::EncodeError", "StandardError"),
    ("Resolv::DNS::Requester::RequestError", "StandardError"),
    ("Resolv::ResolvError", "StandardError"),
    ("Resolv::ResolvTimeout", "Timeout::Error"),
    ("RuntimeError", "StandardError"),
    ("ScriptError", "Exception"),
    ("SecurityError", "Exception"),
    ("SignalException", "Exception"),
    ("Socket::ResolutionError", "SocketError"),
    ("SocketError", "StandardError"),
    ("StandardError", "Exception"),
    ("StopIteration", "IndexError"),
    ("StringScanner::Error", "StandardError"),
    ("SyntaxError", "ScriptError"),
    ("SystemCallError", "StandardError"),
    ("SystemExit", "Exception"),
    ("SystemStackError", "Exception"),
    ("ThreadError", "StandardError"),
    ("Timeout::Error", "RuntimeError"),
    ("Timeout::ExitException", "Exception"),
    ("TypeError", "StandardError"),
    ("URI::BadURIError", "URI::Error"),
    ("URI::Error", "StandardError"),
    ("URI::InvalidComponentError", "URI::Error"),
    ("URI::InvalidURIError", "URI::Error"),
    ("UncaughtThrowError", "ArgumentError"),
    ("ZeroDivisionError", "StandardError"),
    ("Zlib::BufError", "Zlib::Error"),
    ("Zlib::DataError", "Zlib::Error"),
    ("Zlib::Error", "StandardError"),
    ("Zlib::GzipFile::CRCError", "Zlib::GzipFile::Error"),
    ("Zlib::GzipFile::Error", "Zlib::Error"),
    ("Zlib::GzipFile::LengthError", "Zlib::GzipFile::Error"),
    ("Zlib::GzipFile::NoFooter", "Zlib::GzipFile::Error"),
    ("Zlib::InProgressError", "Zlib::Error"),
    ("Zlib::MemError", "Zlib::Error"),
    ("Zlib::NeedDict", "Zlib::Error"),
    ("Zlib::StreamEnd", "Zlib::Error"),
    ("Zlib::StreamError", "Zlib::Error"),
    ("Zlib::VersionError", "Zlib::Error"),
];

/// `Kernel.const_get(source)`: the class a rescued name resolves to, as an index into the table.
///
/// The name is the source as written, which is why `::StandardError` resolves to nothing --
/// `const_get` refuses a leading `::`.
pub(super) fn resolve(name: &str) -> Option<usize> {
    HIERARCHY.iter().position(|(known, _)| *known == name)
}

/// `Module#<=>`: `Less` when the first is a descendant of the second, `Greater` when it is the
/// ancestor, `Same` when they are one class, and nothing when they are unrelated.
pub(super) fn compare(left: usize, right: usize) -> Option<std::cmp::Ordering> {
    if left == right {
        return Some(std::cmp::Ordering::Equal);
    }
    if is_descendant(left, right) {
        return Some(std::cmp::Ordering::Less);
    }
    if is_descendant(right, left) {
        return Some(std::cmp::Ordering::Greater);
    }
    None
}

/// Whether `descendant` inherits from `ancestor`, not counting the class itself.
fn is_descendant(descendant: usize, ancestor: usize) -> bool {
    let mut current = HIERARCHY[descendant].1;
    while !current.is_empty() {
        let Some(index) = resolve(current) else {
            return false;
        };
        if index == ancestor {
            return true;
        }
        current = HIERARCHY[index].1;
    }
    false
}

/// Whether the class is one of the `Errno` classes, which upstream tells apart by their
/// `ancestors[1]` being `SystemCallError`.
pub(super) fn is_system_call_error(index: usize) -> bool {
    HIERARCHY[index].1 == "SystemCallError"
}

/// Whether the class is `Exception` itself.
pub(super) fn is_exception(index: usize) -> bool {
    HIERARCHY[index].0 == "Exception"
}
