mod block_args;
mod comments;
mod conditional;
mod format_string;
mod line_length_help;
mod literal;
mod nodes;
mod percent;
mod percent_array;
mod ranges;
mod trailing_body;
mod trailing_comma;

department_rules! {
    "Style";
    alias => ("Alias", Convention),
    attr => ("Attr", Convention),
    begin_block => ("BeginBlock", Convention),
    block_comments => ("BlockComments", Convention),
    block_delimiters => ("BlockDelimiters", Convention),
    case_equality => ("CaseEquality", Convention),
    class_and_module_children => ("ClassAndModuleChildren", Convention),
    class_methods => ("ClassMethods", Convention),
    colon_method_call => ("ColonMethodCall", Convention),
    colon_method_definition => ("ColonMethodDefinition", Convention),
    commented_keyword => ("CommentedKeyword", Convention),
    def_with_parentheses => ("DefWithParentheses", Convention),
    dir => ("Dir", Convention),
    documentation => ("Documentation", Convention),
    double_cop_disable_directive => ("DoubleCopDisableDirective", Convention),
    each_for_simple_loop => ("EachForSimpleLoop", Convention),
    empty_block_parameter => ("EmptyBlockParameter", Convention),
    empty_lambda_parameter => ("EmptyLambdaParameter", Convention),
    empty_method => ("EmptyMethod", Convention),
    end_block => ("EndBlock", Convention),
    even_odd => ("EvenOdd", Convention),
    exponential_notation => ("ExponentialNotation", Convention),
    expand_path_arguments => ("ExpandPathArguments", Convention),
    format_string_token => ("FormatStringToken", Convention),
    frozen_string_literal_comment => ("FrozenStringLiteralComment", Convention),
    global_std_stream => ("GlobalStdStream", Convention),
    global_vars => ("GlobalVars", Convention),
    guard_clause => ("GuardClause", Convention),
    hash_as_last_array_item => ("HashAsLastArrayItem", Convention),
    hash_like_case => ("HashLikeCase", Convention),
    hash_syntax => ("HashSyntax", Convention),
    if_unless_modifier => ("IfUnlessModifier", Convention),
    if_unless_modifier_of_if_unless => ("IfUnlessModifierOfIfUnless", Convention),
    lambda => ("Lambda", Convention),
    min_max => ("MinMax", Convention),
    mixin_usage => ("MixinUsage", Convention),
    multiline_if_then => ("MultilineIfThen", Convention),
    multiline_memoization => ("MultilineMemoization", Convention),
    multiline_when_then => ("MultilineWhenThen", Convention),
    negated_unless => ("NegatedUnless", Convention),
    negated_while => ("NegatedWhile", Convention),
    nested_parenthesized_calls => ("NestedParenthesizedCalls", Convention),
    next => ("Next", Convention),
    nil_comparison => ("NilComparison", Convention),
    not => ("Not", Convention),
    numeric_literal_prefix => ("NumericLiteralPrefix", Convention),
    numeric_predicate => ("NumericPredicate", Convention),
    numeric_literals => ("NumericLiterals", Convention),
    optional_arguments => ("OptionalArguments", Convention),
    or_assignment => ("OrAssignment", Convention),
    parallel_assignment => ("ParallelAssignment", Convention),
    percent_literal_delimiters => ("PercentLiteralDelimiters", Convention),
    perl_backrefs => ("PerlBackrefs", Convention),
    preferred_hash_methods => ("PreferredHashMethods", Convention),
    redundant_conditional => ("RedundantConditional", Convention),
    redundant_file_extension_in_require => ("RedundantFileExtensionInRequire", Convention),
    redundant_return => ("RedundantReturn", Convention),
    redundant_self_assignment => ("RedundantSelfAssignment", Convention),
    redundant_sort => ("RedundantSort", Convention),
    redundant_sort_by => ("RedundantSortBy", Convention),
    regexp_literal => ("RegexpLiteral", Convention),
    rescue_standard_error => ("RescueStandardError", Convention),
    semicolon => ("Semicolon", Convention),
    single_argument_dig => ("SingleArgumentDig", Convention),
    single_line_methods => ("SingleLineMethods", Convention),
    string_concatenation => ("StringConcatenation", Convention),
    string_literals => ("StringLiterals", Convention),
    string_literals_in_interpolation => ("StringLiteralsInInterpolation", Convention),
    strip => ("Strip", Convention),
    symbol_array => ("SymbolArray", Convention),
    trailing_body_on_class => ("TrailingBodyOnClass", Convention),
    trailing_body_on_method_definition => ("TrailingBodyOnMethodDefinition", Convention),
    trailing_body_on_module => ("TrailingBodyOnModule", Convention),
    trailing_comma_in_arguments => ("TrailingCommaInArguments", Convention),
    trailing_comma_in_array_literal => ("TrailingCommaInArrayLiteral", Convention),
    trailing_comma_in_hash_literal => ("TrailingCommaInHashLiteral", Convention),
    trailing_method_end_statement => ("TrailingMethodEndStatement", Convention),
    unless_else => ("UnlessElse", Convention),
    unpack_first => ("UnpackFirst", Convention),
    while_until_do => ("WhileUntilDo", Convention),
    word_array => ("WordArray", Convention),
}
