mod block_args;
mod comments;
mod conditional;
mod format_sequences;
mod hash_transform;
mod line_length_help;
mod literal;
mod nodes;
mod parameters;
mod percent;
mod percent_array;
mod ranges;
mod trailing_body;
mod trailing_comma;

department_rules! {
    "Style";
    alias => ("Alias", Convention),
    array_join => ("ArrayJoin", Convention),
    attr => ("Attr", Convention),
    bare_percent_literals => ("BarePercentLiterals", Convention),
    begin_block => ("BeginBlock", Convention),
    block_comments => ("BlockComments", Convention),
    block_delimiters => ("BlockDelimiters", Convention),
    case_equality => ("CaseEquality", Convention),
    character_literal => ("CharacterLiteral", Convention),
    class_and_module_children => ("ClassAndModuleChildren", Convention),
    class_check => ("ClassCheck", Convention),
    class_equality_comparison => ("ClassEqualityComparison", Convention),
    class_methods => ("ClassMethods", Convention),
    class_vars => ("ClassVars", Convention),
    colon_method_call => ("ColonMethodCall", Convention),
    command_literal => ("CommandLiteral", Convention),
    colon_method_definition => ("ColonMethodDefinition", Convention),
    comment_annotation => ("CommentAnnotation", Convention),
    commented_keyword => ("CommentedKeyword", Convention),
    def_with_parentheses => ("DefWithParentheses", Convention),
    dir => ("Dir", Convention),
    documentation => ("Documentation", Convention),
    double_cop_disable_directive => ("DoubleCopDisableDirective", Convention),
    double_negation => ("DoubleNegation", Convention),
    each_for_simple_loop => ("EachForSimpleLoop", Convention),
    each_with_object => ("EachWithObject", Convention),
    empty_block_parameter => ("EmptyBlockParameter", Convention),
    empty_case_condition => ("EmptyCaseCondition", Convention),
    empty_else => ("EmptyElse", Convention),
    empty_lambda_parameter => ("EmptyLambdaParameter", Convention),
    empty_literal => ("EmptyLiteral", Convention),
    empty_method => ("EmptyMethod", Convention),
    encoding => ("Encoding", Convention),
    end_block => ("EndBlock", Convention),
    even_odd => ("EvenOdd", Convention),
    expand_path_arguments => ("ExpandPathArguments", Convention),
    exponential_notation => ("ExponentialNotation", Convention),
    float_division => ("FloatDivision", Convention),
    r#for => ("For", Convention),
    format_string => ("FormatString", Convention),
    format_string_token => ("FormatStringToken", Convention),
    frozen_string_literal_comment => ("FrozenStringLiteralComment", Convention),
    global_std_stream => ("GlobalStdStream", Convention),
    global_vars => ("GlobalVars", Convention),
    guard_clause => ("GuardClause", Convention),
    hash_as_last_array_item => ("HashAsLastArrayItem", Convention),
    hash_like_case => ("HashLikeCase", Convention),
    hash_syntax => ("HashSyntax", Convention),
    hash_transform_keys => ("HashTransformKeys", Convention),
    hash_transform_values => ("HashTransformValues", Convention),
    if_unless_modifier => ("IfUnlessModifier", Convention),
    if_unless_modifier_of_if_unless => ("IfUnlessModifierOfIfUnless", Convention),
    if_with_semicolon => ("IfWithSemicolon", Convention),
    lambda => ("Lambda", Convention),
    lambda_call => ("LambdaCall", Convention),
    keyword_parameters_order => ("KeywordParametersOrder", Convention),
    method_def_parentheses => ("MethodDefParentheses", Convention),
    min_max => ("MinMax", Convention),
    method_call_without_args_parentheses => ("MethodCallWithoutArgsParentheses", Convention),

    missing_respond_to_missing => ("MissingRespondToMissing", Convention),
    mixin_usage => ("MixinUsage", Convention),
    multiline_block_chain => ("MultilineBlockChain", Convention),
    module_function => ("ModuleFunction", Convention),
    multiple_comparison => ("MultipleComparison", Convention),
    multiline_if_modifier => ("MultilineIfModifier", Convention),
    multiline_if_then => ("MultilineIfThen", Convention),
    multiline_memoization => ("MultilineMemoization", Convention),
    multiline_when_then => ("MultilineWhenThen", Convention),
    negated_if => ("NegatedIf", Convention),
    negated_unless => ("NegatedUnless", Convention),
    negated_while => ("NegatedWhile", Convention),
    nested_modifier => ("NestedModifier", Convention),
    nested_ternary_operator => ("NestedTernaryOperator", Convention),
    nested_parenthesized_calls => ("NestedParenthesizedCalls", Convention),
    next => ("Next", Convention),
    nil_comparison => ("NilComparison", Convention),
    non_nil_check => ("NonNilCheck", Convention),
    not => ("Not", Convention),
    numeric_literal_prefix => ("NumericLiteralPrefix", Convention),
    numeric_predicate => ("NumericPredicate", Convention),
    numeric_literals => ("NumericLiterals", Convention),
    optional_arguments => ("OptionalArguments", Convention),
    optional_boolean_parameter => ("OptionalBooleanParameter", Convention),
    or_assignment => ("OrAssignment", Convention),
    parallel_assignment => ("ParallelAssignment", Convention),
    parentheses_around_condition => ("ParenthesesAroundCondition", Convention),
    percent_literal_delimiters => ("PercentLiteralDelimiters", Convention),
    percent_q_literals => ("PercentQLiterals", Convention),
    perl_backrefs => ("PerlBackrefs", Convention),
    preferred_hash_methods => ("PreferredHashMethods", Convention),
    proc => ("Proc", Convention),
    raise_args => ("RaiseArgs", Convention),
    random_with_offset => ("RandomWithOffset", Convention),
    redundant_assignment => ("RedundantAssignment", Convention),
    redundant_capital_w => ("RedundantCapitalW", Convention),
    redundant_conditional => ("RedundantConditional", Convention),
    redundant_exception => ("RedundantException", Convention),
    redundant_fetch_block => ("RedundantFetchBlock", Convention),
    redundant_file_extension_in_require => ("RedundantFileExtensionInRequire", Convention),
    redundant_freeze => ("RedundantFreeze", Convention),
    redundant_percent_q => ("RedundantPercentQ", Convention),
    redundant_return => ("RedundantReturn", Convention),
    redundant_self_assignment => ("RedundantSelfAssignment", Convention),
    redundant_sort => ("RedundantSort", Convention),
    redundant_sort_by => ("RedundantSortBy", Convention),
    regexp_literal => ("RegexpLiteral", Convention),
    rescue_standard_error => ("RescueStandardError", Convention),
    sample => ("Sample", Convention),
    self_assignment => ("SelfAssignment", Convention),
    semicolon => ("Semicolon", Convention),
    signal_exception => ("SignalException", Convention),
    single_argument_dig => ("SingleArgumentDig", Convention),
    single_line_methods => ("SingleLineMethods", Convention),
    slicing_with_range => ("SlicingWithRange", Convention),
    stabby_lambda_parentheses => ("StabbyLambdaParentheses", Convention),
    stderr_puts => ("StderrPuts", Convention),
    string_concatenation => ("StringConcatenation", Convention),
    string_literals => ("StringLiterals", Convention),
    string_literals_in_interpolation => ("StringLiteralsInInterpolation", Convention),
    strip => ("Strip", Convention),
    struct_inheritance => ("StructInheritance", Convention),
    symbol_array => ("SymbolArray", Convention),
    symbol_literal => ("SymbolLiteral", Convention),
    trailing_body_on_class => ("TrailingBodyOnClass", Convention),
    trailing_body_on_method_definition => ("TrailingBodyOnMethodDefinition", Convention),
    trailing_body_on_module => ("TrailingBodyOnModule", Convention),
    trailing_comma_in_arguments => ("TrailingCommaInArguments", Convention),
    trailing_comma_in_array_literal => ("TrailingCommaInArrayLiteral", Convention),
    trailing_comma_in_hash_literal => ("TrailingCommaInHashLiteral", Convention),
    trailing_method_end_statement => ("TrailingMethodEndStatement", Convention),
    unless_else => ("UnlessElse", Convention),
    unpack_first => ("UnpackFirst", Convention),
    variable_interpolation => ("VariableInterpolation", Convention),
    when_then => ("WhenThen", Convention),
    while_until_do => ("WhileUntilDo", Convention),
    while_until_modifier => ("WhileUntilModifier", Convention),
    word_array => ("WordArray", Convention),
    zero_length_predicate => ("ZeroLengthPredicate", Convention),
}
